version: "3"
services:
  ntgvn-mongo:
      image: mongo:latest
      ports:
          - "27017:27017"
      networks:
          - ntgvn-network
      restart: always
  ntgvn-rest:
      image: ntgvn-rest:latest
      volumes:
          - d:/Debug/ntgvn-rest/app:/app/
      ports:
          - "8080:8080"
          - "8443:8443"
      networks:
          - ntgvn-network
      depends_on:
          - ntgvn-mongo
      restart: always
networks:
  ntgvn-network:
      external: true
